config/routes.rb
Rails.application.routes.draw do
# config/routes.rb
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "pages#home"
  get 'admin', to: 'admin#index'
  post 'admin', to: 'admin#index'
  patch '/admin/delete_user/:id', to: 'admin#delete_user', as: 'delete_user'
  resources :profiles
  resources :contacts do
    member do
      delete 'delete'
    end
  end
  get "about", to: 'pages#about'
  get "faq", to: 'pages#faq'
  get "mentions_legales", to: 'pages#mentions_legales'
  get "conditions_generales", to: 'pages#conditions_generales'
  get "politique_de_confidentialite", to: 'pages#politique_de_confidentialite'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
        <!-- ========================= footer style-1 footer-dark start ========================= -->
    <div class="footer footer-style-1 footer-dark mb-80">
      <div class="container">
        <div class="widget-wrapper">
          <div class="row" >
             <div class="col-xl-3 col-lg-4 col-md-6">
              <div class="footer-widget">
                <div class="logo">
                <%= image_tag("logo/mini-white.png", height: "220px") %>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-6">
              <div class="footer-widget">
                <h6>Allo Garant</h6>
                <ul class="links">
                  <!-- <li> <%= link_to "Accueil", root_path %> </li> -->
                  <li> <%= link_to "Qui sommes nous?", about_path %> </li>
                  <li> <%= link_to "FAQ", faq_path %> </li>
                  <li> <%= link_to "Nous Contacter", new_contact_path %> </li>
                </ul>
              </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-6">
              <div class="footer-widget">
                <h6>Aide & Support</h6>
                <ul class="links">
                  <li> <%= link_to "Mentions légales", mentions_legales_path %> </li>
                  <li> <%= link_to "CGU", conditions_generales_path %> </li>
                  <li> <%= link_to "Données personnelles", politique_de_confidentialite_path %> </li>
                </ul>
              </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-6">
              <div class="footer-widget">
                <h6>Nous sommes joignables</h6>
                <div class="single-item">
                  <div class="text">
                    <p><i class="fas fa-phone-alt"></i> +212 6 61 33 47 64</p>
                    <p><i class="fas fa-phone-alt"></i> +33 6 09 27 86 36</p>
                  </div>
                </div>
                <div class="single-item">
                  <div class="text">
                    <p><i class="far fa-envelope"></i> contact@allogarant.com</p>
                  </div>
                </div>
                <ul class="socials">
                  <li style="text-decoration: none; "> <a href="https://www.facebook.com/allogarant"> <i class="fab fa-facebook"></i> </a> </li>
                  <li style="text-decoration: none;" > <a href="https://www.instagram.com/allogarant"> <i class="fab fa-instagram"></i> </a> </li>
                  <li style="text-decoration: none;"> <a href="https://fr.linkedin.com/company/allogarant"> <i class="fab fa-linkedin"></i> </a> </li>
                </ul>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ========================= footer style-1 footer-dark end ========================= -->

app/views/shared/_navbar.html.erb
<section class="hero-section-wrapper-1" style="background-color: #F3F3F3;">
  <!-- ========================= header-4 start ========================= -->
  <div class="header header-4" style="position: sticky; background-color: white;">
<div class="navbar-area" style="padding-top: 10px; padding-bottom: 10px;">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-12 navbar navbar-expand-lg navbar-light" style="padding: 0; display: flex; justify-content: space-between; align-items: center;">
            <a class="navbar-brand" href="<%= root_path %>" style="max-height: 40px; margin-left: 20px;">
              <%= image_tag 'logo/logo.png', alt: 'Brand Logo', style: 'max-height: 70px;' %>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" style="flex-direction: row-reverse; margin-right: 20px;">
              <ul class="navbar-nav" style="margin-top: 30px;">
                <% if current_user %>
                  <li class="nav-item">
                    <%= link_to "Profile", edit_profile_path(current_user), class: "page-scroll" %>
                  </li>
                  <% if current_user.admin? %>
                    <li class="nav-item">
                      <%= link_to "Admin Dashboard", admin_path, class: "page-scroll" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Messages", contacts_path, class: "page-scroll" %>
                    </li>
                  <% end %>
                  <li class="nav-item">
                    <%= link_to "Se déconnecter", destroy_user_session_path, method: :get, class: "page-scroll" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "S'inscrire", new_user_registration_path, class: "page-scroll" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Se connecter", new_user_session_path, class: "page-scroll" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!-- row -->
      </div>
      <!-- container -->
    </div>
    <!-- navbar area -->
  </div>
  <!-- ========================= header-4 end ========================= -->
</section>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>